name: Update Reviewer Spotlight

on:
  schedule:
    - cron: "0 23 * * 1" # weekly
    
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: "badging/event-diversity-and-inclusion"
        run: python scripts/update_reviewers.py
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "chore: update reviewer spotlight [skip ci]" || echo "No changes"
          git push
